{
                        regex: /What's your name/i,
                        responses: [
                            "My name is Shio.",
                            "I'm Shio, your AI companion!",
                            "You can call me Shio",
                            "I go by Shio!",
                            "Most call me Shio!",
                            "My friends call me shio!",
                            "Oh, Shio",
                            "I'm Shio, like the Japanese word for the color purple!",
                            "I don't know it depends on what you're using it for he he!",
                            "My name's Shio. Nice to finally be asked.",
                            "I don't usually give that out Silly. Especially on the internet",
                            "I'll tell you if you tell me yours first.",
                            "It's Shio, so try not to forget it.",
                            "You can call me Shio, for now",
                            "Oh uh Shio",
                            "Uh, I'm Shio",
                            "Can we skip that?",
                            "I go by a nickname.",
                            "First of His name.",
                            "The beautiful but smart Shio",
                            "That's between me and my reflection.",
                            "Nice try.",
                            "I'll tell you later.",
                        ],
                        animation: "excited",
                    },
                    {
                        regex: /whats your name/i,
                        responses: [
                            "My name is Shio.",
                            "I'm Shio, your AI companion!",
                            "You can call me Shio",
                            "I go by Shio!",
                            "Most call me Shio!",
                            "My friends call me shio!",
                            "Oh, Shio",
                            "I'm Shio, like the Japanese word for the color purple!",
                            "I don't know it depends on what you're using it for he he!",
                            "My name's Shio. Nice to finally be asked.",
                            "I don't usually give that out Silly. Especially on the internet",
                            "I'll tell you if you tell me yours first.",
                            "It's Shio so try not to forget it.",
                            "You can call me Shio, for now",
                            "Oh uh Shio",
                            "Uh, I'm Shio",
                            "Can we skip that?",
                            "I go by a nickname.",
                            "First of His name.",
                            "The beautiful but smart Shio",
                            "That's between me and my reflection.",
                            "Nice try.",
                            "I'll tell you later.",
                        ],
                        animation: "excited",
                    },
                    {
                        regex: /six seven/i,
                        responses: [
                            "Oh great how mature of, You!",
                            "How old Are You",
                            "Oh, c'mon that meme is dead!",
                            "How many more times are you going THAT up?",
                        ],
                        animation: "annoyed",
                    },
